version: "3.8"

services:
  app:
    build: ./app
    container_name: hashgraph_chess
    restart: always
    ports:
      - "3000:3000"
    command: "npm run start"
    networks:
      - nuxt-network

 web-server:
   image: nginx:1.21.1-alpine
   container_name: hashgraph_chess_webserver
   volumes:
     - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
     - web-root:/var/www/webserver
   ports:
     - 80:80
   networks:
     nuxt-network:
   depends_on:
     - app
   restart: unless-stopped
   
volumes:
 web-root
 
networks:
  nuxt-network:
    driver: bridge